### ISSUE TITLE
xr_linregress needs testing

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/xarrayutils#16]
There were some problems with xr_linregress, that could be better diagnosed by having test(s).

@hogikyan could you describe in a bit more detail, what sort of issues you had?

**Comment by hogikyan** [comment]
No particular issues, but there's a need to ensure that we are consistent with the time array format; I chose to make da_detrend() require datetime input so that I could be sure that I was using the correct 'x' array to detrend the data, as what was being passed to xr_linregress in da_detrend.

**Comment by jbusecke** [comment]
Ok sounds good. Ill implement a test soon, and then we can go from there!

**Comment by hogikyan** [comment]
Actually, I'm doing lagged regressions now and xr_linregress won't take non-matching time. Which makes sense based on how it was implemented, but we should decide how we want to handle that.

**Comment by hogikyan** [comment]
oh awesome!

**Comment by jbusecke** [comment]
Closed via #37
