### ISSUE TITLE
Push a 2.0.1 version?

### ISSUE THREAD

**Issue by rsignell** [jbusecke/xarrayutils#172]
Your AMS 2023 demo env is currently broken but would work if a new version of xarrayutils was pushed with the latest from master.  
What thinkest thou?

**Comment by jbusecke** [comment]
You [got it](https://github.com/jbusecke/xarrayutils/releases/tag/v2.0.1)

**Comment by rsignell** [comment]
Thanks Julius!!

Rich Signell
180 County Rd
Bourne, MA 02532
