### ISSUE TITLE
reversing the sign of vertical coordinate

### ISSUE THREAD

**Issue by miniufo** [jbusecke/xarrayutils#61]
Hi @jbusecke 

I am trying your utils in vertical-coordinate transformation, from z-level to density levels.  From your [notebook](https://github.com/jbusecke/xarrayutils/blob/master/doc/vertical_coords.ipynb), I found that one need to **assume that the depth values are increasing with the depth dimension**.  I tried with MITgcm data which are defined on a decresing z-levels (e.g., -5, -15, ..., -5000) and get somewhat strange results.  So I have to do **the simplest fix is to flip the sign of all depth values**.

This is somewhat annoying.  Is this necessary for a monotonically decreasing coordinate and why is that?

**Comment by jbusecke** [comment]
There is a quick fix (which is not quite intuitive). Flip the bins you use! I think that should work. 
There is some logic that deals with the 'boundary cells' that makes this a little clunky. I plan to have a higher level wrapper at some point, which would detect these, flip them, apply the remapping and flip them back. But for now youll have to do it manually.

**Comment by miniufo** [comment]
Now, it is fine but I’m still looking forward to your wrapper.

**Comment by jbusecke** [comment]
Glad its working for you now. I ll definitely keep this in mind when I get the time to work on this.

**Comment by jbusecke** [comment]
Closing this, since I am planning to deprecate this functionality in xarrayutils (see #84).
