### ISSUE TITLE
shaded_line_plot std spreads error 

### ISSUE THREAD

**Issue by Paul-Aime** [jbusecke/xarrayutils#74]
### Problem

About `shaded_line_plot` function, [Plotting example notebook `In[18]`](https://github.com/jbusecke/xarrayutils/blob/master/doc/plotting.ipynb) states:

> In the default setting, this plots the mean along the dimension member as a line and the ranges indicate 1 standard deviation (dark shading) and 3 standard deviations (light shading).

The default value for `spreads` being `spreads=[1, 3]`.

However, this is not the observed behavior.

Indeed, when looking the code for [`shaded_line_plot` `L347`](https://github.com/jbusecke/xarrayutils/blob/6c33e83b830b7586693366c520a54c1122194d50/xarrayutils/plotting.py#L347), where lines to fill in between are created, the code is:

```python
y_lower = y - (y_std / (2 * spread))
y_upper = y + (y_std / (2 * spread))
```

Following, `y_upper - y_lower ==  y_std / spread` instead of `y_std * spread`.

Another way to spot this wrong behavior is that `alphas` values are increasing (default `alphas=[0.25, 0.4]`) instead of decreasing.

### Solution

Change relevant lines with:

```python
y_delta = y_std * (spread / 2)
y_lower = y - y_delta
y_upper = y + y_delta
```

However, the shadings are then drawn from inner to outer.

As stated in a comment, `np.flip` must then be used to "ensure that the shadings are drawn from outer to inner otherwise they blend too much into each other".

The for loop then becomes:

```python
for spread, alpha in zip(np.flip(spreads), np.flip(alphas)):
	...
```

Also, default `alphas` must then be set to `alphas=[0.4, 0.25],`.

**Comment by jbusecke** [comment]
Thanks for reporting this issue. 

I believe you are right in your analysis. Would you be willing to help fixing this by submitting a PR?

**Comment by Paul-Aime** [comment]
I never did before but it seems that it could be a reasonable first time. I don't have the time right now but I'll make it in a few days.

A question is about how to handle the `alphas` argument.

For intuitive plot (darker filled areas closer to the mean line), users may have already written code with `alphas` items in increasing order, as it was what was shown by the default value (default to `[0.25, 0.4]`).

Then changing this will invert colors for plots generated with old scripts.

However, not changing it will keep the counter-intuitive behavior of having the first item of `alphas` to correspond with the last item of `spreads`.

As I just copy-pasted and fixed this function for my personal project, I obviously chose the 2nd way.

What do you think?

Also, since it is expected from the user but not ensured in the function, is it worth to add a line to sort the `spreads` argument (and `alphas` accordingly)? in order to ensure that areas are plotted from outer to inner.

And, if so, since that will be 2 modification, should it be 1 or 2 PR ?

**Comment by jbusecke** [comment]
> I never did before but it seems that it could be a reasonable first time. I don't have the time right now but I'll make it in a few days.

I agree this is a great first issue. And thank you for taking the time to work on a PR. No worries if it takes some time! I am happy to help where I can.

> For intuitive plot (darker filled areas closer to the mean line), users may have already written code with alphas items in increasing order, as it was what was shown by the default value (default to [0.25, 0.4]).

I think we should change the behavior for consistency (e.g. the alpha values should correpond to the range values). This change would be considered a breaking change and we would bump the version to 0.2.x after this to give other users the option to retain the old behavior with the older version. Perhaps it would be good to make a small comment in the corresponding example notebook, but aside from that I think we should avoid more internal logic and actually make the function work as intended. 

> Also, since it is expected from the user but not ensured in the function, is it worth adding a line to sort the spreads argument (and alphas accordingly)? in order to ensure that areas are plotted from outer to inner.

I would prefer to not add this. The user can always sort the input before passing them to the function. By giving an easy to understand default, this is probably clear enough for the user.

Very much looking forward to your PR.

**Comment by jbusecke** [comment]
@Paul-Aime would it be ok if I take this over? I need this to be fixed for a current project of mine.

**Comment by Paul-Aime** [comment]
@jbusecke Yes sure, sorry btw I forgot about it and never did the PR, 2 years already x)
